# Generated by Django 3.1.1 on 2020-11-18 08:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('explain', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('adv', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('disadv', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('similar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
