# Generated by Django 3.1.1 on 2020-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201119_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Searching', 'Searching'), ('Sorting', 'Sorting'), ('Recursion', 'Recursion'), ('Backtracking', 'Backtracking'), ('Maths', 'Maths'), ('Bit Manipulation', 'Bit Manipulation'), ('Greedy', 'Greedy'), ('Dynamic Programming', 'Dynamic Programming'), ('Graphs', 'Graphs'), ('Others', 'Others')], default='Others', max_length=25),
        ),
    ]
